version: '2.1'

volumes:
  printer:

services:
  printer:
    image: cryowatt/3dprinteros:6.2.4.166
    ports:
      - 80:80
      - 443:443
    volumes:
      - printer:/root/.3dprinteros/
    devices:
      - /dev/bus/usb
      - /dev/ttyUSB0
    privileged: true