version: '2.1'

volumes:
  printer:

services:
  printer:
    build:
      context: .
      args:
        CLIENT_VERSION: "7.9.0.384"
    ports:
      - 80:80
      - 443:443
    volumes:
      - printer:/root/.3dprinteros/
    devices:
      - /dev/bus/usb
      - /dev/ttyUSB0
    privileged: true
