version: '2.1'

volumes:
  printer:

services:
  printer:
    build:
      context: .
      dockerfile: balena.Dockerfile
      args:
        BALENA_MACHINE_NAME: raspberrypi3
    ports:
      - 80:80
      - 443:443
    volumes:
      - printer:/root/.3dprinteros/
    devices:
      - /dev/bus/usb
    privileged: true