version: '2.1'
volumes:
  printer:
services:
  printer:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - printer:/root/.3dprinteros/
    devices:
      - /dev/bus/usb
    privileged: true